type: workflow
name: subdomain_recon
alias: subrec
description: Subdomain discovery
tags: [recon, dns, takeovers]
input_types:
  - host
tasks:
#SUBFINDER
  subfinder:
    description: List subdomains (passive)
#NUCLEI Domain takeover & dns
  _group:
    nuclei:
      description: Check for subdomain takeovers
      targets_:
      - target.name
      - subdomain.host
      tags: [takeover, dns]
 
 #HTTPX http probes on subdomains
    httpx:
      description: Run HTTP probes on subdomains
      targets_:
      - target.name
      - subdomain.host
      tags: [screenshot, tech-detect]
  
 #NABU scan open ports
    nmap:
      description: Find open ports
      targets_:
      - target.name
      - subdomain.host
 #HTTPX
    httpx:
		    description: Probe HTTP services on open ports
		    targets_:
			    - type: port
				    field: '{host}:{port}'
				tags: [screenshot, tech-detect]
			
#NUCLEI SSL & Headers
    nuclei/url:
      description: Search for vulnerabilities on alive HTTP services
      tags: [network, ssl, headers]
      targets_:
        - type: url
          field: url
          condition: item.status_code != 0
	    
    
